//import styles from "../styles/Home.module.css";
import Layout from "../../Components/Layout/Layout";
import Head from "next/head";
import {
  Flex,
  Heading,
  Box,
  Text,
  Link,
  UnorderedList,
  ListItem,
} from "@chakra-ui/react";
import styles from "./privacy_policy.module.css";
import { NextPage } from "next";

const privacy_policy: NextPage = () => {
  return (
    <>
      <Layout>
        <Head>
          <title>BlocTrace</title>
          {/* <meta name="description" content="noindex,nofollow" /> */}
        </Head>

        <Heading
          as="h1"
          fontSize="5rem"
          color="brand.0"
          fontWeight="medium"
          size="lg"
          p="2rem"
          mb="1rem"
          textAlign="center"
        >
          Privacy Policy
        </Heading>

        <Flex
          justifyContent="flex-start"
          flexDirection="column"
          color="brand.20"
          textAlign="left"
          maxWidth="800px"
          margin="0 auto"
        >
          {/* ... (previous text) ... */}
          <Heading className="header2">Business Transactions</Heading>
          <Text className="body">Last updated: June 12, 2023</Text>
          <Text className="body">
            This Privacy Policy describes Our policies and procedures on the
            collection, use and disclosure of Your information when You use the
            Service and tells You about Your privacy rights and how the law
            protects You.
          </Text>
          <Text className="body">
            We don't use your Personal data to provide and improve the Service.
            By using the Service, You agree to the collection and use of
            information in accordance with this Privacy Policy. This Privacy
            Policy has been created with the help of the Free Privacy Policy
            Generator.
          </Text>
          <Heading className="header1">Interpretation and Definitionst</Heading>
          <Heading className="header2">Interpretation</Heading>
          <Text className="body">
            The words of which the initial letter is capitalized have meanings
            defined under the following conditions. The following definitions
            shall have the same meaning regardless of whether they appear in
            singular or in plural.
          </Text>
          <Heading className="header2">Definitions</Heading>
          <Heading className="header2">Other Legal Requirements</Heading>
          <Text className="body">For the purposes of this Privacy Policy:</Text>
          <UnorderedList className="body">
            <ListItem>
              Account means a unique account created for You to access our
              Service or parts of our Service.
            </ListItem>
            <ListItem>
              Affiliate means an entity that controls, is controlled by or is
              under common control with a party, where "control" means ownership
              of 50% or more of the shares, equity interest or other securities
              entitled to vote for election of directors or other managing
              authority.
            </ListItem>
            <ListItem>
              Company (referred to as either "the Company", "We", "Us" or "Our"
              in this Agreement) refers to Earendel Labs Finance.
            </ListItem>
            <ListItem>
              Cookies are small files that are placed on Your computer, mobile
              device or any other device by a website, containing the details of
              Your browsing history on that website among its many uses.
            </ListItem>
            <ListItem>Country refers to: Singapore</ListItem>
            <ListItem>
              Device means any device that can access the Service such as a
              computer, a cellphone or a digital tablet.
            </ListItem>
            <ListItem>
              Personal Data is any information that relates to an identified or
              identifiable individual.
            </ListItem>
            <ListItem>Service refers to the Website.</ListItem>
            <ListItem>
              Service Provider means any natural or legal person who processes
              the data on behalf of the Company. It refers to third-party
              companies or individuals employed by the Company to facilitate the
              Service, to provide the Service on behalf of the Company, to
              perform services related to the Service or to assist the Company
              in analyzing how the Service is used.
            </ListItem>
            <ListItem>
              Usage Data refers to data collected automatically, either
              generated by the use of the Service or from the Service
              infrastructure itself (for example, the duration of a page visit).
            </ListItem>
            <ListItem>
              Website refers to Earendel Labs Finance, accessible from
              https://buzzkill-frontend-rjaoyldwc-earendel-labs.vercel.app/
            </ListItem>
            <ListItem>
              You means the individual accessing or using the Service, or the
              company, or other legal entity on behalf of which such individual
              is accessing or using the Service, as applicable.
            </ListItem>
          </UnorderedList>
          {/* ... (remaining text) ... */}
          <Heading className="header1">
            Collecting and Using Your Personal Data
          </Heading>
          <Heading className="header2">Types of Data Collected</Heading>
          <Heading className="header3">Personal Data</Heading>
          <Text className="body">
            While using Our Service, We may ask You to provide Us with certain
            personally identifiable information that can be used to contact or
            identify You. Personally identifiable information may include, but
            is not limited to: Usage Data.
          </Text>
          <Heading className="header3">Usage Data</Heading>
          <Text className="body">
            Usage Data is collected automatically when using the Service.
          </Text>
          <Text className="body">
            Usage Data may include information such as Your Device's Internet
            Protocol address (e.g. IP address), browser type, browser version,
            the pages of our Service that You visit, the time and date of Your
            visit, the time spent on those pages, unique device identifiers and
            other diagnostic data.
          </Text>
          <Text className="body">
            When You access the Service by or through a mobile device, We may
            collect certain information automatically, including, but not
            limited to, the type of mobile device You use, Your mobile device
            unique ID, the IP address of Your mobile device, Your mobile
            operating system, the type of mobile Internet browser You use,
            unique device identifiers and other diagnostic data.
          </Text>
          <Text className="body">
            We may also collect information that Your browser sends whenever You
            visit our Service or when You access the Service by or through a
            mobile device.
          </Text>
          <Heading className="header1">
            Tracking Technologies and Cookies
          </Heading>
          <Text className="body">
            We use Cookies and similar tracking technologies to track the
            activity on Our Service and store certain information. Tracking
            technologies used are beacons, tags, and scripts to collect and
            track information and to improve and analyze Our Service. The
            technologies We use may include:
          </Text>{" "}
          <UnorderedList className="body">
            <ListItem>
              <strong>Cookies or Browser Cookies.</strong> A cookie is a small
              file placed on Your Device. You can instruct Your browser to
              refuse all Cookies or to indicate when a Cookie is being sent.
              However, if You do not accept Cookies, You may not be able to use
              some parts of our Service. Unless you have adjusted Your browser
              setting so that it will refuse Cookies, our Service may use
              Cookies.{" "}
            </ListItem>
            <ListItem>
              <strong>Web Beacons.</strong> Certain sections of our Service and
              our emails may contain small electronic files known as web beacons
              (also referred to as clear gifs, pixel tags, and single-pixel
              gifs) that permit the Company, for example, to count users who
              have visited those pages or opened an email and for other related
              website statistics (for example, recording the popularity of a
              certain section and verifying system and server integrity).
            </ListItem>
          </UnorderedList>
          <Heading className="header2">Changes to this Privacy Policy</Heading>
          <Text className="body">
            We may update Our Privacy Policy from time to time. We will notify
            You of any changes by posting the new Privacy Policy on this page.
          </Text>
          {/* ... (remaining text) ... */}
          <Text className="body">
            If you have any questions about this Privacy Policy, You can contact
            us:
          </Text>
          <Text className="body">
            By visiting this page on our website:{" "}
            <a href="https://twitter.com/BuzzkillNFT" className={styles.link}>
              https://twitter.com/BuzzkillNFT
            </a>
          </Text>
        </Flex>
      </Layout>
    </>
  );
};

export default privacy_policy;
